gword = [{text: 'sakai', size: 100},
{text: 'with', size: 42},
{text: 'error', size: 35},
{text: 'password', size: 30},
{text: 'forgotten', size: 30},
{text: 'feature', size: 30},
{text: 'problem', size: 29},
{text: 'mysql', size: 26},
{text: 'site', size: 26},
{text: 'maven', size: 26},
{text: 'version', size: 26},
{text: 'desktop', size: 26},
{text: 'samigo', size: 25},
{text: 'update', size: 25}
];
